# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_new', models.BooleanField()),
                ('size', models.CharField(max_length=40)),
                ('instructions', models.FileField(upload_to='')),
                ('featured_photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('beds', 'Beds & mattressess'), ('furn', 'Furniture, wardrobes & shelves'), ('sofa', 'Sofas & armchairs'), ('table', 'Tables & chairs'), ('texti', 'Textiles'), ('deco', 'Decoration & mirrors'), ('light', 'Lighting'), ('cook', 'Cookware'), ('tablw', 'Tableware'), ('taps', 'Taps & sinks'), ('org', 'Organisers & storage accesories'), ('toys', 'Toys'), ('leis', 'Leisure'), ('safe', 'safety'), ('diy', 'Do-it-yourself'), ('floor', 'Flooring'), ('plant', 'Plants & gardering'), ('food', 'Food & beverages')], max_length=5)),
            ],
        ),
    ]
