# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shoppingcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ykea.Shoppingcart'),
        ),
    ]
