# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_auto_20180517_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itembill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
